// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypuulunifkpqhzklxedl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdXVsdW5pZmtwcWh6a2x4ZWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDMwNjEsImV4cCI6MjA2MzQ3OTA2MX0.ft43FAT8-sGCDBDQzuqZ4ZChG6nwaLjRqYEfRryj1SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);